# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25609c2dad5065d0801663f3a5921d250d158c0d6939dffe6c84c18ac2b12f7b39fd40adbe0343153f93bba0d615052782604e2fedc48ed083b7cf9b6350195d

test:
  secret_key_base: 312528516029f06a604f84847c5be4086e918231cbeb5a34ab4b7dc7f150a6b1b62d8b70fa1718d550540338ef4844052a666e429f978c931d2f25fda4942789

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
